"""Boxline: cloud browsers and shell sandboxes for AI agents.

    from boxline import Boxline

    bx = Boxline()  # reads BOXLINE_API_KEY and BOXLINE_API_URL
    with bx.sessions.create(shell=True) as s:
        s.goto("https://example.com")
        print(s.content()["title"])
        print(s.exec("uname -a")["stdout"])

``AsyncBoxline`` has the same methods to ``await``. Connect Playwright to a session with
``chromium.connect_over_cdp(s.connect_url)``.
"""

from . import types
from ._async_client import (
    AsyncAgent,
    AsyncApiKeys,
    AsyncAuth,
    AsyncBoxline,
    AsyncCrawl,
    AsyncCredentials,
    AsyncExecStream,
    AsyncExtensions,
    AsyncFiles,
    AsyncKeyboard,
    AsyncMouse,
    AsyncProfiles,
    AsyncProject,
    AsyncSession,
    AsyncSessionFiles,
    AsyncSessions,
    AsyncTasks,
    AsyncWebhooks,
)
from ._base import IDEMPOTENT_POSTS, NOT_GIVEN, RequestOptions, is_idempotent_post, retry_delay
from ._client import Agent, ApiKeys, Auth, Boxline, Crawl, Credentials, ExecStream, Extensions, Files, Keyboard, Mouse, Profiles, Project, Session, SessionFiles, Sessions, Tasks, Webhooks
from ._errors import (
    AuthenticationError,
    BoxlineConnectionError,
    BoxlineError,
    BoxlineTimeoutError,
    CaptchaTimeoutError,
    CodeUrlNotAllowedError,
    CredentialCodeTimeoutError,
    CredentialExistsError,
    CredentialLinkWrongSiteError,
    CredentialLoginFailedError,
    CredentialLoginTimeoutError,
    CredentialNotAllowedError,
    CrossSiteRequestError,
    ErrorCode,
    ExtensionDeniedError,
    FeatureNotInPlanError,
    IdempotencyInProgressError,
    IdempotencyMismatchError,
    InvalidCursorError,
    InvalidExtensionError,
    LimitReachedError,
    MachineTooOldError,
    MissingVariablesError,
    ModelRefusedError,
    NotContinuableError,
    NotFoundError,
    OutOfViewportError,
    PageTimeoutError,
    NotAWebPageError,
    PageUnreachableError,
    PayloadExpiredError,
    PayloadTooLargeError,
    PlanLimitError,
    ProjectSuspendedError,
    RateLimitError,
    SearchUnavailableError,
    SessionNotRunningError,
    NothingSavedError,
    TooManyMessagesError,
    RunNotLiveError,
    TooManyCredentialValuesError,
    VariablesWithExtensionsError,
    WebhookDisabledError,
    WebhookSignatureError,
    WebhooksUnavailableError,
    WebhookUrlNotAllowedError,
    make_error,
)
from ._webhooks import SIGNATURE_HEADER as WEBHOOK_SIGNATURE_HEADER
from ._webhooks import TOLERANCE_SECONDS as WEBHOOK_TOLERANCE_SECONDS
from ._webhooks import verify_webhook, webhook_signature_header
from ._pagination import AsyncPage, AsyncPager, Page, Pager
from ._version import __version__

__all__ = [
    "Agent",
    "ApiKeys",
    "AsyncAgent",
    "AsyncApiKeys",
    "AsyncAuth",
    "AsyncBoxline",
    "AsyncCrawl",
    "AsyncCredentials",
    "AsyncExecStream",
    "AsyncExtensions",
    "AsyncFiles",
    "AsyncKeyboard",
    "AsyncMouse",
    "AsyncPage",
    "AsyncPager",
    "AsyncProfiles",
    "AsyncProject",
    "AsyncSession",
    "AsyncSessionFiles",
    "AsyncSessions",
    "AsyncTasks",
    "AsyncWebhooks",
    "Auth",
    "AuthenticationError",
    "Boxline",
    "BoxlineConnectionError",
    "BoxlineError",
    "BoxlineTimeoutError",
    "CaptchaTimeoutError",
    "CrossSiteRequestError",
    "Crawl",
    "CodeUrlNotAllowedError",
    "CredentialCodeTimeoutError",
    "CredentialExistsError",
    "CredentialLinkWrongSiteError",
    "CredentialLoginFailedError",
    "CredentialLoginTimeoutError",
    "CredentialNotAllowedError",
    "Credentials",
    "ErrorCode",
    "ExecStream",
    "ExtensionDeniedError",
    "Extensions",
    "FeatureNotInPlanError",
    "Files",
    "IDEMPOTENT_POSTS",
    "IdempotencyInProgressError",
    "IdempotencyMismatchError",
    "InvalidCursorError",
    "InvalidExtensionError",
    "Keyboard",
    "LimitReachedError",
    "MachineTooOldError",
    "MissingVariablesError",
    "ModelRefusedError",
    "Mouse",
    "NOT_GIVEN",
    "NotContinuableError",
    "NotFoundError",
    "OutOfViewportError",
    "SessionNotRunningError",
    "NothingSavedError",
    "TooManyMessagesError",
    "RunNotLiveError",
    "Page",
    "PageTimeoutError",
    "NotAWebPageError",
    "PageUnreachableError",
    "PayloadExpiredError",
    "PayloadTooLargeError",
    "Pager",
    "PlanLimitError",
    "Profiles",
    "Project",
    "ProjectSuspendedError",
    "RateLimitError",
    "RequestOptions",
    "SearchUnavailableError",
    "Session",
    "SessionFiles",
    "VariablesWithExtensionsError",
    "Sessions",
    "Tasks",
    "TooManyCredentialValuesError",
    "WEBHOOK_SIGNATURE_HEADER",
    "WEBHOOK_TOLERANCE_SECONDS",
    "WebhookDisabledError",
    "WebhookSignatureError",
    "WebhookUrlNotAllowedError",
    "Webhooks",
    "WebhooksUnavailableError",
    "__version__",
    "is_idempotent_post",
    "make_error",
    "retry_delay",
    "types",
    "verify_webhook",
    "webhook_signature_header",
]
