"""Generates the sync client (src/boxline/_client.py) from the async one (src/boxline/_async_client.py).

    python scripts/unasync.py           # write _client.py
    python scripts/unasync.py --check   # exit 1 when _client.py is not what the async source gives

The async file is the only source: one code path, two clients. The rules below remove ``async``/``await`` and rename
the async-only names; blocks between ``# --- async only ---`` and ``# --- end ---`` are dropped. Keep the source
to what these rules understand (no ``AsyncGenerator``, no ``anext``), and check the result with the tests.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

PKG = Path(__file__).resolve().parent.parent / "src" / "boxline"
SOURCE = PKG / "_async_client.py"
TARGET = PKG / "_client.py"

HEADER = '''# Generated from _async_client.py by scripts/unasync.py: do not edit this file. Edit _async_client.py and run
#     python scripts/unasync.py
'''

DOCSTRING = '''"""The Boxline client (``Boxline``): the same code as ``AsyncBoxline`` in _async_client.py, without ``await``."""
'''

# Applied in order, on whole words.
RULES = [
    (r"\basync def\b", "def"),
    (r"\basync for\b", "for"),
    (r"\basync with\b", "with"),
    (r"\bawait ", ""),
    (r"\b__aenter__\b", "__enter__"),
    (r"\b__aexit__\b", "__exit__"),
    (r"\b__aiter__\b", "__iter__"),
    (r"\b__anext__\b", "__next__"),
    (r"\bStopAsyncIteration\b", "StopIteration"),
    (r"\baclose\b", "close"),
    (r"\baiter_lines\b", "iter_lines"),
    (r"\baiter_bytes\b", "iter_bytes"),
    (r"\baread\b", "read"),
    (r"\basyncio\.sleep\b", "time.sleep"),
    # AsyncBoxline → Boxline, AsyncSession → Session, AsyncIterator → Iterator, httpx.AsyncClient → httpx.Client, …
    (r"\bAsync([A-Z][A-Za-z0-9_]*)\b", r"\1"),
]


def generate(source: str) -> str:
    lines = []
    skipping = False
    for line in source.splitlines(keepends=True):
        mark = line.strip()
        if mark == "# --- async only ---":
            skipping = True
            continue
        if skipping:
            if mark == "# --- end ---":
                skipping = False
            continue
        lines.append(line)
    if skipping:
        raise SystemExit("unasync: '# --- async only ---' without '# --- end ---'")
    text = "".join(lines)
    # The source's module docstring is about the source; the generated file gets its own (added after the renames).
    if text.startswith('"""'):
        text = text[text.index('"""', 3) + 4 :]
    for pattern, repl in RULES:
        text = re.sub(pattern, repl, text)
    return HEADER + DOCSTRING + text


def main() -> int:
    expected = generate(SOURCE.read_text(encoding="utf-8"))
    if "--check" in sys.argv[1:]:
        current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else ""
        if current != expected:
            print(f"{TARGET.name} is out of date: run python scripts/unasync.py", file=sys.stderr)
            return 1
        return 0
    TARGET.write_text(expected, encoding="utf-8")
    print(f"wrote {TARGET.relative_to(PKG.parent.parent)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
